name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - v4
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout the current branch
        uses: actions/checkout@v6 # checkout the repo
        with:
          ref: gh-pages

      - name: Initialize the ssh-agent # configure ssh private key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.ORACLE_ARM_X_KEY }}
  
  # SSH keyscan to avoid error
      - name: Scan the host key
        run: mkdir -p ~/.ssh/ && ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.ORACLE_ARM_X_IP }}
  
  # Runs the rsync command to the remote site (caddy reverse proxy)
      - name: Deploy the website
        run: >-
            rsync -avx --delete --exclude '.ssh' --exclude '.git' . $DEPLOY_USERNAME@$DEPLOY_SERVER:./docker/npmplus/www/html/digitalgarden
        env:
          DEPLOY_SERVER: ${{ secrets.ORACLE_ARM_X_IP }}
          DEPLOY_USERNAME: ubuntu
